title: Just the Docs Exercise
description: An exercise for a Jeykll site using the Just the Docs theme
theme: just-the-docs

url: https://majaborgosz.github.io/stagenstron

aux_links:
  Template Repository: https://github.com/majaborgosz/stagenstron
